version: "3"

tasks:
  clear_and_run:
    description: "clear database and run server"
    cmds:
      - go run cmd/migrations/main.go --action=down
      - go run cmd/migrations/main.go --action=up
      - go run cmd/sso/main.go