env: local #local, dev, prod

token_expires: 1h
refresh_token_expires: 168h
migrations_path: ./migrations

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: postgres
  timeout: 5s
  delay: 5s
  sslmode: disable
  attempts: 5

grpc:
  port: 9090
  timeout: 5s